# This is a basic workflow to help you get started with Actions

name: Testes API Postman

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  test:
    name: Testes API
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Copiando os arquivos para maquina virtual
        uses: actions/checkout@v4

      - name: Etapa 00 - Instalação Node 16.x
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      # Runs a set of commands using the runners shell
      - name: Etapa 01 - Verificação versão do Node e Newman
        run: 
          newman --version && node --version && ls
              
      # Runs a single command using the runners shell
      - name: Etapa 02 - Html Extra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Runs a set of command using the runners shell
      - name: Etapa 03 - Rodando as Collections de Testes
        run: newman run "hunters-collection.json" -e "hunters-env.json" -r cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html --reporter-htmlextra-displayProgressBar 

      # Runs a set of command using the runners shell
      - name: Etapa 04 - Salvando o Resultado dos Testes
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: ./results/Report.html
             
